First implementation #1
atk4/outbox pull request #2
Opened 2020-02-04 22:05 UTC by abbadon1334

Working on #1

2020-02-17 17:47 UTC, DarkSide666 requested changes
Found some bugs, but overall looks nice.

2020-02-17 17:47 UTC, DarkSide666 commented on src/Mailer/AbstractMailer.php
> +                'replyto',
shouldn't there be `bcc` ?

2020-02-17 17:47 UTC, DarkSide666 commented on src/Mailer/Gmail.php
> +        $this->phpmailer->isSMTP();
no needs for this line because it's already in Mailer/SMTP class

2020-02-17 17:47 UTC, DarkSide666 commented on src/Model/Mail.php
> +        $outbox->send($this);
here $outbox still can be `null` so need some additional checking i think

2020-02-17 17:47 UTC, DarkSide666 commented on src/Outbox.php
> +    private $mailer;
please use `protected` instead of `private` properties so this class can be extended more easily

2020-02-17 17:47 UTC, DarkSide666 commented on src/Outbox.php
> +                'getOutBox',
Should be `getOutbox` not `getOutBox` (letter B case)

2020-02-17 18:43 UTC, DarkSide666 approved these changes
nice

2020-02-17 18:43 UTC, DarkSide666 commented on src/Outbox.php
> +    private function validateOutbox(): void
pls `protected`

2020-02-17 20:27 UTC, abbadon1334 commented on src/Outbox.php
> +    private function validateOutbox(): void
done

2020-02-18 08:48 UTC, romaninsh approved these changes
Thanks so much for contributing this!

2020-04-04 15:09 UTC, merged